export const team = [
  { name: 'Robert Wheatfall', bio: 'Robert has a background in this thing and that thing, and has a strong interest in creating the future of retail. He graduated with a B.A. from Morehouse College and an MBA from Harvard Business School. Robert\'s responsibilities include project one, project two, and project three.', photo: 'location of photo' }, { name: 'Nick Angelos', bio: 'Nick has a background in software development and corporate strategy, and is interested in something. He graduated with a B.S. in Economics from Brigham Young University. Nick\'s responsibilities include project two, project four, and project five.', photo: 'location of photo' }
]

export const aboutUs = ['The Rogue Elephant Company was started out of a belief that the home improvement and home repair industries should have access to all the convenience and technological advancements that every other industry uses. The home improvement industry is ... big, believe there is a greater oppportunity in repair and reuse than in new home construction. This comes with its own set of issues and limitations, which is where we come in.', 'When your furnace goes out, or your refrigerator needs to be repaired, it can be difficult to find a repairman, schedule a visit, and then miss a day of work while waiting for the technician to come between the hours of 10 and 4. Once the technician comes to your house, it takes 30 minutes to assess the problem, give you and estimate, and then inform you that he doesn\'t have the required part in his truck, and will have to come back later in the week, meaning you will miss another day of work. We think this process should be easy, transparent, and convenient for the customer...']

export const whatWeDo = 'Whether you are doing it yourself or scheduling an appointment, home repair and home improvement should be easy. We\'re here to make that happen.'

export const whereWeAre = 'Being strategically located in Chicago ensures we never forget our roots, while maintaining access to all that our country has to offer.'
